version: "3.9"

services:

  # db:
  #   image: postgres:13-alpine
  #   volumes:
  #     - dev-db-data2:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=habib
  #     - POSTGRES_PASSWORD=habib
  #     - POSTGRES_DB=habib
  #   ports:
  #     - "5432:5432"
  #   container_name: db
  #   restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html

    ports:
      - "8080:8080"
    links:
      - db
    restart: always
    container_name: backend-docker



  webapp-fe:
    build: ./Web-app (We-Care)
    ports:
      - "80:80"
    container_name: webapp-frontend
    restart: always
    links:
      - backend


volumes:
  dev-db-data2:
