name: CI

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend -f ./backend/Dockerfile  ./backend

      - name: Tag Backend Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/backend ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Push Backend to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend


      - name: Build FrontEnd Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend -f ./"Web-app (We-Care)"/Dockerfile ./"Web-app (We-Care)"

      - name: Tag FrontEnd Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/frontend ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Push FrontEnd to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend
    
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: wecare
          environment_name: wecare-env-3
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-2
          deployment_package: deploy.zip
